"""
Unified persistence layer for all StratOS agents.

Every agent calls `save_envelope(envelope)` with the unified shape:
{
  "agent_id":        str,
  "run_id":          str (UUID, generated by build_envelope if missing),
  "run_timestamp":   str (ISO-8601, generated if missing),
  "status":          "success" | "partial" | "error",
  "errors":          list,
  "swot_items":      list[dict],     # see swot item shape below
  "structured_data": dict | list,    # agent-specific payload
}

SWOT item shape:
{
  "type":            "strength" | "weakness" | "opportunity" | "threat",
  "title":           str | None,
  "description":     str,
  "evidence":        list,
  "impact_level":    str | None,
  "pillar_id":       int | None,     # populated by categorizer for S/W only
  "pillar_name":     str | None,
  "source_metadata": dict,
}

If DB_CONNECTION_STRING is missing, save_envelope is a no-op (logs a warning).
"""
from __future__ import annotations

import os
import uuid
from datetime import datetime, timezone
from typing import Any

import psycopg2
from psycopg2.extras import Json
from dotenv import load_dotenv

load_dotenv()

DB_CONNECTION_STRING = os.getenv("DB_CONNECTION_STRING", "")


def _get_conn():
    if not DB_CONNECTION_STRING:
        return None
    return psycopg2.connect(DB_CONNECTION_STRING)


def build_envelope(
    agent_id: str,
    swot_items: list[dict] | None = None,
    structured_data: Any = None,
    status: str = "success",
    errors: list | None = None,
    run_id: str | None = None,
) -> dict:
    """Build a unified envelope with sensible defaults for any missing field."""
    return {
        "agent_id": agent_id,
        "run_id": run_id or str(uuid.uuid4()),
        "run_timestamp": datetime.now(timezone.utc).isoformat(),
        "status": status,
        "errors": errors or [],
        "swot_items": [_normalize_swot_item(it) for it in (swot_items or [])],
        "structured_data": structured_data if structured_data is not None else {},
    }


def _normalize_swot_item(item: dict) -> dict:
    return {
        "type": item.get("type"),
        "title": item.get("title"),
        "description": item.get("description", ""),
        "evidence": item.get("evidence", []),
        "impact_level": item.get("impact_level"),
        "pillar_id": item.get("pillar_id"),
        "pillar_name": item.get("pillar_name"),
        "source_metadata": item.get("source_metadata", {}),
    }


def save_envelope(envelope: dict) -> str | None:
    """
    Categorize any S/W items (if needed), then persist the envelope.

    Returns the run_id on success, or None if the DB is not configured.
    """
    if not DB_CONNECTION_STRING:
        print("[persistence] DB_CONNECTION_STRING not set — skipping save.")
        return None

    # Categorize S/W items in-place (only if any are missing pillar_id)
    swot_items = envelope.get("swot_items", [])
    needs_categorization = any(
        it.get("type") in ("strength", "weakness") and it.get("pillar_id") is None
        for it in swot_items
    )
    if needs_categorization:
        # Local import to avoid a circular dep at module load time
        from Agents.categorizer import categorize_swot_items
        categorize_swot_items(swot_items)

    conn = None
    try:
        conn = _get_conn()
        with conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO agent_runs
                        (run_id, agent_id, run_timestamp, status, errors, structured_data, raw_envelope)
                    VALUES (%s, %s, %s, %s, %s, %s, %s)
                    """,
                    (
                        envelope["run_id"],
                        envelope["agent_id"],
                        envelope["run_timestamp"],
                        envelope.get("status", "success"),
                        Json(envelope.get("errors", [])),
                        Json(envelope.get("structured_data", {})),
                        Json(envelope),
                    ),
                )

                for item in swot_items:
                    cur.execute(
                        """
                        INSERT INTO swot_items
                            (item_id, run_id, agent_id, type, title, description,
                             evidence, impact_level, pillar_id, pillar_name, source_metadata)
                        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                        """,
                        (
                            str(uuid.uuid4()),
                            envelope["run_id"],
                            envelope["agent_id"],
                            item["type"],
                            item.get("title"),
                            item["description"],
                            Json(item.get("evidence", [])),
                            item.get("impact_level"),
                            item.get("pillar_id"),
                            item.get("pillar_name"),
                            Json(item.get("source_metadata", {})),
                        ),
                    )

        print(f"[persistence] Saved run {envelope['run_id']} ({envelope['agent_id']}, "
              f"{len(swot_items)} swot items).")
        return envelope["run_id"]

    except Exception as e:
        print(f"[persistence] Save failed for {envelope.get('agent_id')}: {e}")
        return None
    finally:
        if conn is not None:
            conn.close()
