"use client";

import React, { useState, useRef, useEffect, useCallback, useImperativeHandle, forwardRef } from "react";
import {
  Send, Plus, Copy, Check, MessageSquare,
} from "lucide-react";
import type { PlanDocument, Provenance } from "@/types/plan-document";

// ── Types ─────────────────────────────────────────────────────────────────────

export interface SelectedBlockInfo {
  blockId: string;
  heading: string;
  provenance: Provenance | null;
}

export interface ChatPanelHandle {
  injectText: (text: string) => void;
}

type ChatRole = "user" | "assistant";

interface ChatMessage {
  id: string;
  role: ChatRole;
  text: string;
  isDraft?: boolean;
}

interface ChatPanelProps {
  selectedBlock: SelectedBlockInfo | null;
  doc: PlanDocument;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function uid() {
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`;
}

function describeProvenance(prov: Provenance): string {
  if (prov.kind === "human") {
    return `Human edit on ${new Date(prov.editedAt).toLocaleDateString()}`;
  }
  if (prov.kind === "agent_signal") {
    const finding = prov.finding.length > 100 ? prov.finding.slice(0, 100) + "…" : prov.finding;
    return `${prov.agent} agent signal — ${finding}`;
  }
  if (prov.kind === "reference_plan") {
    return `Reference plan: "${prov.planTitle}", section: ${prov.sectionHeading}`;
  }
  if (prov.kind === "mixed") {
    return `Multiple sources: ${prov.sources.map(s => s.kind).join(", ")}`;
  }
  return "AI-generated from strategic signals";
}

function mockResponse(userText: string, blockHeading: string | null): string {
  const lower = userText.toLowerCase();

  if (lower.includes("explain") || lower.includes("source") || lower.includes("where does") || lower.includes("evidence")) {
    return blockHeading
      ? `The section **"${blockHeading}"** was generated by the StratOS planning AI, synthesizing signals from your organization's strategic data across workforce, technology, sentiment, and benchmark agents.\n\nEach insight was weighted by confidence score and mapped to your strategic pillars before being composed into this content.`
      : "This content was synthesized from your organization's strategic signal data. Select a specific section to see its source evidence.";
  }

  if (lower.includes("rewrite") || lower.includes("revise") || lower.includes("formal") || lower.includes("professional")) {
    return `[Draft] Here is a more formal revision:\n\n"The organization shall pursue evidence-based strategic objectives aligned with its core institutional capabilities, measurable performance outcomes, and long-term stakeholder value creation — consistent with the strategic framework and applicable governance standards."\n\n*Click **Copy** to use this text.*`;
  }

  if (lower.includes("shorten") || lower.includes("shorter") || lower.includes("concise") || lower.includes("brief")) {
    return `[Draft] Condensed version:\n\n"The organization will prioritize strategic initiatives aligned with core capabilities and measurable outcomes, guided by stakeholder priorities and institutional governance.\n\n*Click **Copy** to use this text.*`;
  }

  if (lower.includes("bullet") || lower.includes("list") || lower.includes("points")) {
    return `[Draft] As bullet points:\n• Align strategic objectives with core organizational capabilities\n• Establish measurable KPIs tied to each initiative\n• Ensure governance and compliance across all workstreams\n• Engage key stakeholders at each phase of implementation\n\n*Click **Copy** to use this text.*`;
  }

  if (lower.includes("translate") || lower.includes("arabic") || lower.includes("english")) {
    return "Translation is handled via the EN/AR toggle at the top of the editor — it switches the document direction and language metadata. Full AI translation will be available in a future update.";
  }

  return "I can help you **explain** a section's sources, **rewrite** content in a different tone, make it more **concise**, convert it to **bullet points**, or draft new additions.\n\nSelect a section in the document and ask away.";
}

// ── Main component ─────────────────────────────────────────────────────────────

export const ChatPanel = forwardRef<ChatPanelHandle, ChatPanelProps>(function ChatPanel({ selectedBlock, doc }, ref) {
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: "welcome",
      role: "assistant",
      text: "Hi! I'm your plan editing assistant.\n\nSelect any section in the document to see its sources, then ask me to explain, rewrite, or expand it. Use **+** to reference specific sections.",
    },
  ]);
  const [input, setInput] = useState("");
  const [mentionOpen, setMentionOpen] = useState(false);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [width, setWidth] = useState(340);

  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const mentionRef = useRef<HTMLDivElement>(null);
  const dragRef = useRef<{ startX: number; startWidth: number } | null>(null);
  const prevBlockIdRef = useRef<string | null>(null);

  useImperativeHandle(ref, () => ({
    injectText(text: string) {
      setInput(prev => (prev ? prev + "\n\n" + text : text));
      setTimeout(() => {
        inputRef.current?.focus();
        if (inputRef.current) {
          inputRef.current.scrollTop = inputRef.current.scrollHeight;
        }
      }, 50);
    },
  }), []);

  // Auto-resize textarea: reset to auto so scrollHeight recalculates, then apply it
  useEffect(() => {
    const ta = inputRef.current;
    if (!ta) return;
    ta.style.height = "auto";
    ta.style.height = `${ta.scrollHeight}px`;
  }, [input]);

  // Auto-scroll to bottom when messages change
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  // Track block changes (used for mockResponse context only)
  useEffect(() => {
    if (!selectedBlock) return;
    prevBlockIdRef.current = selectedBlock.blockId;
  }, [selectedBlock]);

  // Close mention dropdown on outside click
  useEffect(() => {
    if (!mentionOpen) return;
    const handler = (e: MouseEvent) => {
      if (mentionRef.current && !mentionRef.current.contains(e.target as Node)) {
        setMentionOpen(false);
      }
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [mentionOpen]);

  // Draggable panel width
  const handleDragStart = useCallback((e: React.MouseEvent) => {
    e.preventDefault();
    dragRef.current = { startX: e.clientX, startWidth: width };

    const onMove = (ev: MouseEvent) => {
      if (!dragRef.current) return;
      const delta = dragRef.current.startX - ev.clientX;
      const next = Math.max(260, Math.min(560, dragRef.current.startWidth + delta));
      setWidth(next);
    };

    const onUp = () => {
      dragRef.current = null;
      document.removeEventListener("mousemove", onMove);
      document.removeEventListener("mouseup", onUp);
    };

    document.addEventListener("mousemove", onMove);
    document.addEventListener("mouseup", onUp);
  }, [width]);

  const handleSend = () => {
    const text = input.trim();
    if (!text) return;

    const uMsg: ChatMessage = { id: uid(), role: "user", text };
    const isDraft =
      text.toLowerCase().includes("rewrite") ||
      text.toLowerCase().includes("revise") ||
      text.toLowerCase().includes("formal") ||
      text.toLowerCase().includes("shorten") ||
      text.toLowerCase().includes("bullet");

    const aMsg: ChatMessage = {
      id: uid(),
      role: "assistant",
      text: mockResponse(text, selectedBlock?.heading ?? null),
      isDraft,
    };

    setMessages(prev => [...prev, uMsg, aMsg]);
    setInput("");
    setTimeout(() => inputRef.current?.focus(), 50);
  };

  const handleCopy = (id: string, text: string) => {
    const clean = text.replace(/\*\*/g, "").replace(/\[Draft\] /, "").replace(/\*Click.*\*$/, "").trim();
    navigator.clipboard.writeText(clean).catch(() => null);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const insertMention = (label: string) => {
    setInput(prev => prev + (prev.endsWith(" ") || prev === "" ? "" : " ") + `@${label} `);
    setMentionOpen(false);
    inputRef.current?.focus();
  };

  // Simple markdown: **bold**, newlines → <br>
  const renderText = (text: string) => {
    const parts = text.split(/(\*\*[^*]+\*\*)/g);
    return parts.map((part, i) => {
      if (part.startsWith("**") && part.endsWith("**")) {
        return <strong key={i}>{part.slice(2, -2)}</strong>;
      }
      return (
        <span key={i}>
          {part.split("\n").map((line, j, arr) => (
            <React.Fragment key={j}>
              {line}
              {j < arr.length - 1 && <br />}
            </React.Fragment>
          ))}
        </span>
      );
    });
  };

  return (
    <aside
      className="plan-chat-panel relative flex h-full flex-col overflow-hidden border-s border-white/5 bg-[#0b0e1a]"
      style={{ width }}
    >
      {/* Drag handle */}
      <div
        className="absolute start-0 top-0 bottom-0 w-1.5 cursor-col-resize hover:bg-cyan-500/20 transition-colors z-10"
        onMouseDown={handleDragStart}
      />

      {/* Header */}
      <div className="flex items-center gap-2 border-b border-white/5 px-4 py-3">
        <MessageSquare className="h-3.5 w-3.5 text-cyan-400" />
        <span className="text-[10px] font-semibold uppercase tracking-widest text-slate-500">
          Plan Assistant
        </span>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-3 py-3 space-y-3">
        {messages.map((msg) => {
          if (msg.role === "user") {
            return (
              <div key={msg.id} className="flex justify-end">
                <div className="max-w-[85%] rounded-lg rounded-tr-sm bg-[#1e2535] px-3 py-2 text-xs text-slate-200 leading-relaxed">
                  {msg.text}
                </div>
              </div>
            );
          }

          // assistant
          return (
            <div key={msg.id} className="flex flex-col gap-1">
              <div className="flex items-start gap-2">
                <div className="mt-0.5 h-5 w-5 shrink-0 rounded-full bg-gradient-to-br from-cyan-500 to-blue-600 flex items-center justify-center">
                  <MessageSquare className="h-2.5 w-2.5 text-white" />
                </div>
                <div className="flex-1 rounded-lg rounded-tl-sm bg-[#131825] p-3 text-[12px] leading-relaxed text-slate-300">
                  {renderText(msg.text)}
                </div>
              </div>
              {msg.isDraft && (
                <div className="ms-7 flex gap-1.5">
                  <button
                    onClick={() => handleCopy(msg.id, msg.text)}
                    className="flex items-center gap-1 rounded border border-white/10 bg-white/5 px-2 py-0.5 text-[10px] text-slate-400 hover:border-white/20 hover:text-slate-200 transition-colors"
                  >
                    {copiedId === msg.id ? (
                      <><Check className="h-2.5 w-2.5 text-emerald-400" /> Copied</>
                    ) : (
                      <><Copy className="h-2.5 w-2.5" /> Copy draft</>
                    )}
                  </button>
                </div>
              )}
            </div>
          );
        })}
        <div ref={messagesEndRef} />
      </div>

      {/* Input area */}
      <div className="border-t border-white/5 p-3">
        <div className="flex items-end gap-2 rounded-lg border border-white/10 bg-[#131825] p-2 focus-within:border-cyan-500/30 transition-colors">
          {/* @ mention trigger */}
          <div className="relative" ref={mentionRef}>
            <button
              onClick={() => setMentionOpen(v => !v)}
              className="flex h-6 w-6 items-center justify-center rounded text-slate-500 hover:bg-white/5 hover:text-slate-300 transition-colors"
              title="Reference a section"
            >
              <Plus className="h-3.5 w-3.5" />
            </button>

            {mentionOpen && (
              <div className="absolute bottom-8 start-0 z-50 min-w-[220px] max-h-60 overflow-y-auto rounded-lg border border-white/10 bg-[#1a2030] p-1 shadow-xl">
                <div className="px-2 py-1 text-[10px] font-semibold uppercase tracking-widest text-slate-600">
                  Reference section
                </div>
                {doc.chapters.map((ch) => (
                  <React.Fragment key={ch.id}>
                    <button
                      onClick={() => insertMention(`Chapter ${ch.number}: ${ch.title}`)}
                      className="flex w-full items-center gap-2 rounded px-2 py-1.5 text-left text-xs text-slate-300 hover:bg-white/5 transition-colors"
                    >
                      <span className="shrink-0 text-[#b8922f] font-bold">{String(ch.number).padStart(2, "0")}</span>
                      <span className="truncate">{ch.title}</span>
                    </button>
                    {ch.sections.map((sub, idx) => (
                      <button
                        key={sub.id}
                        onClick={() => insertMention(`${ch.number}.${idx + 1}: ${sub.heading}`)}
                        className="flex w-full items-center gap-2 rounded px-2 py-1.5 ps-7 text-left text-xs text-slate-500 hover:bg-white/5 hover:text-slate-300 transition-colors"
                      >
                        <span className="shrink-0">{ch.number}.{idx + 1}</span>
                        <span className="truncate">{sub.heading}</span>
                      </button>
                    ))}
                  </React.Fragment>
                ))}
              </div>
            )}
          </div>

          <textarea
            ref={inputRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault();
                handleSend();
              }
            }}
            placeholder="Ask me to explain, rewrite, or expand…"
            rows={1}
            className="flex-1 resize-none bg-transparent text-xs text-slate-200 placeholder-slate-600 outline-none leading-relaxed"
            style={{ maxHeight: "14rem", overflowY: "auto" }}
          />

          <button
            onClick={handleSend}
            disabled={!input.trim()}
            className="flex h-6 w-6 items-center justify-center rounded bg-cyan-500/15 text-cyan-400 hover:bg-cyan-500/25 disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
          >
            <Send className="h-3 w-3" />
          </button>
        </div>
        <p className="mt-1.5 text-center text-[9px] text-slate-700">
          Shift+Enter for new line · Enter to send
        </p>
      </div>
    </aside>
  );
});
